#!/usr/bin/env bash

visible=$CONFIG/polybar/.visible
barheight=27
padding=0

if [ -f $visible ]; then
    polybar-msg cmd hide
    rm $visible
else
    #bspc config top_padding ((padding+$barheight))
    polybar-msg cmd show
    ((padding=padding+barheight))
    touch $visible
fi

bspc config top_padding $padding




