#!/usr/bin/env bash
sxhkd &                     # enable keybinds

. $SCRIPTS/comp             # mblur
. $SCRIPTS/keeb             # caps lock -> ctrl+esc
. $SCRIPTS/bar/launch       # bar

redshift -l 53:0 &          # make our eyes less strained

mopdiy &                    # bops
xbanish &                   # fuck off cursor
udiskie &                   # external drive management

#asusd-user &
