#!/usr/bin/env bash
sxhkd &                     # enable keybinds

. $SCRIPTS/comp             # mblur
. $SCRIPTS/keeb             # caps lock -> ctrl+esc

redshift -l 53:0 &          # make our eyes less strained

mopidy &                    # bops
xbanish &                   # fuck off cursor
udiskie &                   # external drive management
dunst &                     # notifs

#asusd-user &
