#! /bin/sh

export BSPWM_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm"

# theme colours
. "${HOME}/.cache/wal/colors.sh"

# launch bar
. $SCRIPTS/bar/launch

bspc monitor --reset-desktops 1 2 3 4 5 6 7 8 9 0

bspc config border_width		0
bspc config window_gap          0

visible=$CONFIG/polybar/.visible

vpadding=0
hpadding=0
bspc config top_padding         $vpadding
bspc config bottom_padding      $vpadding
bspc config left_padding        $hpadding
bspc config right_padding       $hpadding

bspc config split_ratio			0.52
bspc config borderless_monocle	true
bspc config gapless_monocle		true

# generic rules
bspc rule -a Dialog state=floating
bspc rule -a Prompt state=floating

bspc config focused_border_color		"$color2"
bspc config active_border_color			"$color1"
bspc config normal_border_color			"$color1"

if [ "$1" = "reload" ]; then
	echo "reloaded config."
else
	"$BSPWM_CONFIG/autostart" &
fi
